export const PROMOS_DATA = [
  {
    id: 1,
    bank: "BCA EXPOVERSARY 2024",
    tagBg: "bg-[#005B9F]",
    tagText: "text-white",
    title: "DISKON BUNGA",
    desc: "Bunga Spesial mulai 2.67% eff.p.a fix 1 tahun",
    btnText: "Ambil Promo",
    footerText: "BERAKHIR 31 MAR",
    bgImage: "/images/simulasiKPRs/Card 1_ BCA.png",
  },
  {
    id: 2,
    bank: "MANDIRI FESTIVAL",
    tagBg: "bg-[#FFC700]",
    tagText: "text-[#1A1C1A]",
    title: "BEBAS PPN",
    desc: "Insentif Pemerintah 100% untuk hunian ready stock",
    btnText: "Lihat Semua",
    footerText: "S&K BERLAKU",
    bgImage: "/images/simulasiKPRs/Card 2_ Mandiri.png",
  },
  {
    id: 3,
    bank: "BNI GRIYA",
    tagBg: "bg-[#F15A22]",
    tagText: "text-white",
    title: "BEBAS BIAYA KPR",
    desc: "Gratis biaya provisi, administrasi & appraisal",
    btnText: "Ambil Promo",
    footerText: "KUOTA TERBATAS",
    bgImage: "/images/simulasiKPRs/Card 3_ BNI.png",
  },
  {
    id: 4,
    bank: "BTN KPR",
    tagBg: "bg-[#003366]",
    tagText: "text-white",
    title: "BUNGA KHUSUS BTN",
    desc: "Suku bunga ringan mulai 2.99% fix 2 tahun untuk KPR pertama",
    btnText: "Ambil Promo",
    footerText: "KUOTA TERBATAS",
    bgImage: "/images/simulasiKPRs/Card 1_ BCA.png",
  },
];