export const units = [
  {
    id: 1,
    name: "Classic Haven 42/65",
    category: "Classic Haven",
    badge: "CLASSIC HAVEN",
    bedrooms: 2,
    bathrooms: "1 KM",
    price: "Rp 1,2 M",
    image: "/images/units/classic-haven-42.jpg",
    slug: "classic-haven-42-65",
  },
  {
    id: 2,
    name: "Classic Haven 100/88",
    category: "Classic Haven",
    badge: "CLASSIC HAVEN",
    bedrooms: "3+1",
    bathrooms: "3 KM",
    price: "Rp 2,5 M",
    image: "/images/units/classic-haven-100.jpg",
    slug: "classic-haven-100-88",
  },
  {
    id: 3,
    name: "Geefi Residence 42/60",
    category: "Geefi Residence",
    badge: "GEEFI RESIDENCE",
    bedrooms: 2,
    bathrooms: "1 KM",
    price: "Rp 800 Juta",
    image: "/images/units/geefi-residence-42.jpg",
    slug: "geefi-residence-42-60",
  },
  {
    id: 4,
    name: "Geefi Residence 54/60",
    category: "Geefi Residence",
    badge: "GEEFI RESIDENCE",
    bedrooms: 2,
    bathrooms: "2 KM",
    price: "Rp 1 M",
    image: "/images/units/geefi-residence-54.jpg",
    slug: "geefi-residence-54-60",
  },
  {
    id: 5,
    name: "Geefi Subsidi Plumpung 30/60",
    category: "Geefi Subsidi",
    badge: "GEEFI SUBSIDI",
    bedrooms: 2,
    bathrooms: "1 KM",
    price: "Rp 180 Juta",
    image: "/images/units/geefi-subsidi-30.jpg",
    slug: "geefi-subsidi-plumpung-30-60",
  },
  {
    id: 6,
    name: "Geefi Subsidi 2 Plumpung",
    category: "Geefi Subsidi",
    badge: "GEEFI SUBSIDI",
    bedrooms: 2,
    bathrooms: "1 KM",
    price: "Rp 380 Juta",
    image: "/images/units/geefi-subsidi-2.jpg",
    slug: "geefi-subsidi-2-plumpung",
  },
];

export const categories = ["Semua", "Classic Haven", "Geefi Residence", "Geefi Subsidi"];